return {
PlaceObj('ModItemCode', {
	'name', "AmmoProperties",
	'CodeFileName', "Code/AmmoProperties.lua",
}),
PlaceObj('ModItemCode', {
	'name', "AmountGunPowderFromAmmo",
	'CodeFileName', "Code/AmountGunPowderFromAmmo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "AmountScrapPartsFromAmmo",
	'CodeFileName', "Code/AmountScrapPartsFromAmmo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "GetInventoryObject",
	'CodeFileName', "Code/GetInventoryObject.lua",
}),
PlaceObj('ModItemCode', {
	'name', "GetScrapParts",
	'CodeFileName', "Code/GetScrapParts.lua",
}),
PlaceObj('ModItemCode', {
	'name', "InitMod",
	'CodeFileName', "Code/InitMod.lua",
}),
PlaceObj('ModItemCode', {
	'name', "InventoryStackAddAndStackGunpowder",
	'CodeFileName', "Code/InventoryAddAndStack.lua",
}),
PlaceObj('ModItemCode', {
	'name', "ScrapItem",
	'CodeFileName', "Code/ScrapItem.lua",
}),
PlaceObj('ModItemOptionChoice', {
	'name', "sam_LogLevel",
	'comment', "0 = off / errors only, 1 = minimal, 2 = info, 3 = debug",
	'DisplayName', "Log Level",
	'Help', "0 = off / errors only, 1 = minimal, 2 = info, 3 = debug",
	'DefaultValue', "0",
	'ChoiceList', {
		"0",
		"1",
		"2",
		"3",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "sam_GunPowderPerAPAmmo",
	'comment', "Gunpowder per 30 AP ammo",
	'DisplayName', "GunPowder per 30 AP ammo",
	'Help', "Defines the amount of gunpowder you get per 30 AP ammo.",
	'DefaultValue', "1 - default",
	'ChoiceList', {
		"0",
		"1 (default)",
		"2",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
	},
}),
PlaceObj('ModItemOptionChoice', {
		'name', "sam_GunPowderPerNormalAmmo",
		'comment', "Gunpowder per 30 normal ammo",
		'DisplayName', "GunPowder per 30 normal ammo",
		'Help', "Defines the amount of gunpowder you get per 30 normal ammo.",
		'DefaultValue', "1 - default",
		'ChoiceList', {
			"0",
			"1 (default)",
			"2",
			"3",
			"4",
			"5",
			"6",
			"7",
			"8",
			"9",
		},
	}),
PlaceObj('ModItemOptionChoice', {
	'name', "sam_ScrapPerAPAmmo",
	'comment', "Scrap per 30 ap ammo",
	'DisplayName', "Scrap per 30 AP ammo",
	'Help', "Defines the amount of scrap you get per 30 AP ammo.",
	'DefaultValue', "4 - default",
	'ChoiceList', {
		"0",
		"1",
		"2",
		"3",
		"4 (default)",
		"5",
		"6",
		"7",
		"8",
		"9",
	},
}),
PlaceObj('ModItemOptionChoice', {
	'name', "sam_ScrapPerNormalAmmo",
	'comment', "Scrap per 30 normal ammo",
	'DisplayName', "Scrap per 30 normal ammo",
	'Help', "Defines the amount of scrap you get per 30 normal ammo.",
	'DefaultValue', "2 - default",
	'ChoiceList', {
		"0",
		"1",
		"2 (default)",
		"3",
		"4",
		"5",
		"6",
		"7",
		"8",
		"9",
	},
}),
PlaceObj('ModItemOptionToggle', {
	'name', "sam_Logging",
	'DisplayName', "Enable Logging",
	'Help', "Turn on to enable logging from mod",
}),
}
