return {
PlaceObj('ModItemCode', {
	'name', "AmmoProperties",
	'CodeFileName', "Code/AmmoProperties.lua",
}),
PlaceObj('ModItemCode', {
	'name', "AmountGunPowderFromAmmo",
	'CodeFileName', "Code/AmountGunPowderFromAmmo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "AmountScrapPartsFromAmmo",
	'CodeFileName', "Code/AmountScrapPartsFromAmmo.lua",
}),
PlaceObj('ModItemCode', {
	'name', "GetScrapParts",
	'CodeFileName', "Code/GetScrapParts.lua",
}),
PlaceObj('ModItemCode', {
	'name', "ScrapItem",
	'CodeFileName', "Code/ScrapItem.lua",
}),
PlaceObj('ModItemCode', {
	'name', "GetInventoryObject",
	'CodeFileName', "Code/GetInventoryObject.lua",
}),
PlaceObj('ModItemCode', {
	'name', "InventoryStackAddAndStack",
	'CodeFileName', "Code/InventoryStackAddAndStackGunPowder.lua",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_12gauge_Breacher",
	'object_class', "Ammo",
	'ScrapParts', 10,
	'Icon', "UI/Icons/Items/12_gauge_bullets_breacher.png",
	'DisplayName', T(644616198480, --[[ModItemInventoryItemCompositeDef _12gauge_Breacher DisplayName]] "12-gauge Breacher"),
	'DisplayNamePlural', T(756176270226, --[[ModItemInventoryItemCompositeDef _12gauge_Breacher DisplayNamePlural]] "12-gauge Breacher"),
	'colorStyle', "AmmoAPColor",
	'Description', T(587086786172, --[[ModItemInventoryItemCompositeDef _12gauge_Breacher Description]] "12-gauge ammo for Shotguns."),
	'AdditionalHint', T(109180931299, --[[ModItemInventoryItemCompositeDef _12gauge_Breacher AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Very short range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Wide attack cone\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Improved armor penetration\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Prevents Grazing hits due to opponents Taking Cover\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Suppressed</color>"),
	'MaxStacks', 500,
	'Caliber', "12gauge",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 1,
			target_prop = "IgnoreCoverReduction",
		}),
		PlaceObj('CaliberModification', {
			mod_mul = 500,
			target_prop = "WeaponRange",
		}),
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "PenetrationClass",
		}),
		PlaceObj('CaliberModification', {
			mod_mul = 2000,
			target_prop = "ObjDamageMod",
		}),
		PlaceObj('CaliberModification', {
			mod_mul = 1700,
			target_prop = "BuckshotConeAngle",
		}),
		PlaceObj('CaliberModification', {
			mod_mul = 1700,
			target_prop = "OverwatchAngle",
		}),
	},
	'AppliedEffects', {
		"Suppressed",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_12gauge_Buckshot",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/12_gauge_bullets_buckshot.png",
	'DisplayName', T(817584556389, --[[ModItemInventoryItemCompositeDef _12gauge_Buckshot DisplayName]] "12-gauge Buckshot"),
	'DisplayNamePlural', T(452529018580, --[[ModItemInventoryItemCompositeDef _12gauge_Buckshot DisplayNamePlural]] "12-gauge Buckshot"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(263757581937, --[[ModItemInventoryItemCompositeDef _12gauge_Buckshot Description]] "12-gauge ammo for Shotguns."),
	'AdditionalHint', T(854915907925, --[[ModItemInventoryItemCompositeDef _12gauge_Buckshot AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>"),
	'MaxStacks', 500,
	'Caliber', "12gauge",
	'Modifications', {},
	'AppliedEffects', {
		"Bleeding",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_12gauge_Flechette",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/12_gauge_bullets_flechette.png",
	'DisplayName', T(994311605449, --[[ModItemInventoryItemCompositeDef _12gauge_Flechette DisplayName]] "12-gauge Sabot"),
	'DisplayNamePlural', T(292882182138, --[[ModItemInventoryItemCompositeDef _12gauge_Flechette DisplayNamePlural]] "12-gauge Sabot"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(353184354978, --[[ModItemInventoryItemCompositeDef _12gauge_Flechette Description]] "12-gauge ammo for Shotguns."),
	'AdditionalHint', T(516082239475, --[[ModItemInventoryItemCompositeDef _12gauge_Flechette AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Longer range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Narrow attack cone\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>"),
	'MaxStacks', 500,
	'Caliber', "12gauge",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_mul = 500,
			target_prop = "BuckshotConeAngle",
		}),
		PlaceObj('CaliberModification', {
			mod_mul = 500,
			target_prop = "OverwatchAngle",
		}),
		PlaceObj('CaliberModification', {
			mod_add = 4,
			target_prop = "WeaponRange",
		}),
	},
	'AppliedEffects', {
		"Bleeding",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_12gauge_Saltshot",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/12_gauge_bullets_saltshot.png",
	'DisplayName', T(897306856548, --[[ModItemInventoryItemCompositeDef _12gauge_Saltshot DisplayName]] "12-gauge Saltshot"),
	'DisplayNamePlural', T(658376345970, --[[ModItemInventoryItemCompositeDef _12gauge_Saltshot DisplayNamePlural]] "12-gauge Saltshot"),
	'colorStyle', "AmmoTracerColor",
	'Description', T(327947775885, --[[ModItemInventoryItemCompositeDef _12gauge_Saltshot Description]] "12-gauge ammo for Shotguns."),
	'AdditionalHint', T(129571711087, --[[ModItemInventoryItemCompositeDef _12gauge_Saltshot AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low damage\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Shorter range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Wide attack cone\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Inaccurate</color>"),
	'MaxStacks', 500,
	'Caliber', "12gauge",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_mul = 500,
			target_prop = "Damage",
		}),
		PlaceObj('CaliberModification', {
			mod_mul = 1700,
			target_prop = "BuckshotConeAngle",
		}),
		PlaceObj('CaliberModification', {
			mod_add = -2,
			target_prop = "WeaponRange",
		}),
		PlaceObj('CaliberModification', {
			mod_mul = 1700,
			target_prop = "OverwatchAngle",
		}),
	},
	'AppliedEffects', {
		"Inaccurate",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_44CAL_AP",
	'object_class', "Ammo",
	'ScrapParts', 10,
	'Icon', "UI/Icons/Items/44_cal_bullets_armor_piercing.png",
	'DisplayName', T(735499371090, --[[ModItemInventoryItemCompositeDef _44CAL_AP DisplayName]] ".44 Armor Piercing"),
	'DisplayNamePlural', T(877463400750, --[[ModItemInventoryItemCompositeDef _44CAL_AP DisplayNamePlural]] ".44 Armor Piercing"),
	'colorStyle', "AmmoAPColor",
	'Description', T(776316868771, --[[ModItemInventoryItemCompositeDef _44CAL_AP Description]] ".44 Ammo for Revolvers and Rifles."),
	'AdditionalHint', T(642295786881, --[[ModItemInventoryItemCompositeDef _44CAL_AP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Improved armor penetration"),
	'MaxStacks', 500,
	'Caliber', "44CAL",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "PenetrationClass",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_44CAL_Basic",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/44_cal_bullets_basic.png",
	'DisplayName', T(898460241965, --[[ModItemInventoryItemCompositeDef _44CAL_Basic DisplayName]] ".44 Standard"),
	'DisplayNamePlural', T(607628355266, --[[ModItemInventoryItemCompositeDef _44CAL_Basic DisplayNamePlural]] ".44 Standard"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(177911542799, --[[ModItemInventoryItemCompositeDef _44CAL_Basic Description]] ".44 Ammo for Revolvers and Rifles."),
	'MaxStacks', 500,
	'Caliber', "44CAL",
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_44CAL_HP",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/44_cal_bullets_hollow_point.png",
	'DisplayName', T(290851622821, --[[ModItemInventoryItemCompositeDef _44CAL_HP DisplayName]] ".44 Hollow Point"),
	'DisplayNamePlural', T(947009347102, --[[ModItemInventoryItemCompositeDef _44CAL_HP DisplayNamePlural]] ".44 Hollow Point"),
	'colorStyle', "AmmoHPColor",
	'Description', T(283556501662, --[[ModItemInventoryItemCompositeDef _44CAL_HP Description]] ".44 Ammo for Revolvers and Rifles."),
	'AdditionalHint', T(748707788425, --[[ModItemInventoryItemCompositeDef _44CAL_HP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>"),
	'MaxStacks', 500,
	'Caliber', "44CAL",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
	},
	'AppliedEffects', {
		"Bleeding",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_44CAL_Match",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/44_cal_bullets_match.png",
	'DisplayName', T(935031543254, --[[ModItemInventoryItemCompositeDef _44CAL_Match DisplayName]] ".44 Match"),
	'DisplayNamePlural', T(729118661137, --[[ModItemInventoryItemCompositeDef _44CAL_Match DisplayNamePlural]] ".44 Match"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(653130596618, --[[ModItemInventoryItemCompositeDef _44CAL_Match Description]] ".44 Ammo for Revolvers and Rifles."),
	'AdditionalHint', T(969507173754, --[[ModItemInventoryItemCompositeDef _44CAL_Match AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming"),
	'MaxStacks', 500,
	'Caliber', "44CAL",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "AimAccuracy",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_44CAL_Shock",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/44_cal_bullets_shock.png",
	'DisplayName', T(671330851390, --[[ModItemInventoryItemCompositeDef _44CAL_Shock DisplayName]] ".44 Shock"),
	'DisplayNamePlural', T(136526955127, --[[ModItemInventoryItemCompositeDef _44CAL_Shock DisplayNamePlural]] ".44 Shock"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(255049518731, --[[ModItemInventoryItemCompositeDef _44CAL_Shock Description]] ".44 Ammo for Revolvers and Rifles."),
	'AdditionalHint', T(767771378452, --[[ModItemInventoryItemCompositeDef _44CAL_Shock AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Reduced range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Hit enemies are <color EmStyle>Exposed</color> and lose the benefits of Cover\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>"),
	'MaxStacks', 500,
	'Caliber', "44CAL",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
		PlaceObj('CaliberModification', {
			mod_add = -4,
			target_prop = "WeaponRange",
		}),
	},
	'AppliedEffects', {
		"Exposed",
		"Bleeding",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_50BMG_Basic",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/50bmg_basic.png",
	'DisplayName', T(430431749223, --[[ModItemInventoryItemCompositeDef _50BMG_Basic DisplayName]] ".50 Standard"),
	'DisplayNamePlural', T(842298872893, --[[ModItemInventoryItemCompositeDef _50BMG_Basic DisplayNamePlural]] ".50 Standard"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(958905444387, --[[ModItemInventoryItemCompositeDef _50BMG_Basic Description]] ".50 Ammo for Machine Guns, Snipers and Handguns."),
	'MaxStacks', 500,
	'Caliber', "50BMG",
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_50BMG_HE",
	'object_class', "Ammo",
	'ScrapParts', 10,
	'Icon', "UI/Icons/Items/50bmg_he.png",
	'DisplayName', T(470141133007, --[[ModItemInventoryItemCompositeDef _50BMG_HE DisplayName]] ".50 Explosive"),
	'DisplayNamePlural', T(249148916468, --[[ModItemInventoryItemCompositeDef _50BMG_HE DisplayNamePlural]] ".50 Explosive"),
	'colorStyle', "AmmoHPColor",
	'Description', T(438865141913, --[[ModItemInventoryItemCompositeDef _50BMG_HE Description]] ".50 Ammo for Machine Guns, Snipers and Handguns."),
	'AdditionalHint', T(845204892785, --[[ModItemInventoryItemCompositeDef _50BMG_HE AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No armor penetration\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance"),
	'MaxStacks', 500,
	'Caliber', "50BMG",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
		PlaceObj('CaliberModification', {
			mod_add = -4,
			target_prop = "PenetrationClass",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_50BMG_Incendiary",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/50bmg_incendiary.png",
	'DisplayName', T(288955756990, --[[ModItemInventoryItemCompositeDef _50BMG_Incendiary DisplayName]] ".50 Frag"),
	'DisplayNamePlural', T(873925576017, --[[ModItemInventoryItemCompositeDef _50BMG_Incendiary DisplayNamePlural]] ".50 Frag"),
	'colorStyle', "AmmoTracerColor",
	'Description', T(897177292445, --[[ModItemInventoryItemCompositeDef _50BMG_Incendiary Description]] ".50 Ammo for Machine Guns, Snipers and Handguns."),
	'AdditionalHint', T(482312884822, --[[ModItemInventoryItemCompositeDef _50BMG_Incendiary AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Hit enemies are <color EmStyle>Exposed</color> and lose the benefits of Cover\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Burning</color>"),
	'MaxStacks', 500,
	'Caliber', "50BMG",
	'Modifications', {},
	'AppliedEffects', {
		"Exposed",
		"Burning",
	},
	'GunPowder', 2,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_50BMG_SLAP",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/50bmg_slap.png",
	'DisplayName', T(630196331609, --[[ModItemInventoryItemCompositeDef _50BMG_SLAP DisplayName]] ".50 SLAP"),
	'DisplayNamePlural', T(726628131150, --[[ModItemInventoryItemCompositeDef _50BMG_SLAP DisplayNamePlural]] ".50 SLAP"),
	'colorStyle', "AmmoAPColor",
	'Description', T(865778878027, --[[ModItemInventoryItemCompositeDef _50BMG_SLAP Description]] ".50 Ammo for Machine Guns, Snipers and Handguns."),
	'AdditionalHint', T(116250141970, --[[ModItemInventoryItemCompositeDef _50BMG_SLAP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Improved armor penetration\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Slightly higher Crit chance"),
	'MaxStacks', 500,
	'Caliber', "50BMG",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 1,
			target_prop = "PenetrationClass",
		}),
		PlaceObj('CaliberModification', {
			mod_add = 15,
			target_prop = "CritChance",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_556_AP",
	'object_class', "Ammo",
	'ScrapParts', 10,
	'Icon', "UI/Icons/Items/556_nato_bullets_armor_piercing.png",
	'DisplayName', T(692754815369, --[[ModItemInventoryItemCompositeDef _556_AP DisplayName]] "5.56 mm Armor Piercing"),
	'DisplayNamePlural', T(179782107141, --[[ModItemInventoryItemCompositeDef _556_AP DisplayNamePlural]] "5.56 mm Armor Piercing"),
	'colorStyle', "AmmoAPColor",
	'Description', T(648577297256, --[[ModItemInventoryItemCompositeDef _556_AP Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(897062191321, --[[ModItemInventoryItemCompositeDef _556_AP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Improved armor penetration"),
	'MaxStacks', 500,
	'Caliber', "556",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "PenetrationClass",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_556_Basic",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/556_nato_bullets_basic.png",
	'DisplayName', T(695092855292, --[[ModItemInventoryItemCompositeDef _556_Basic DisplayName]] "5.56 mm Standard"),
	'DisplayNamePlural', T(302209357050, --[[ModItemInventoryItemCompositeDef _556_Basic DisplayNamePlural]] "5.56 mm Standard"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(784722917210, --[[ModItemInventoryItemCompositeDef _556_Basic Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'MaxStacks', 500,
	'Caliber', "556",
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_556_HP",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/556_nato_bullets_hollow_point.png",
	'DisplayName', T(785562002563, --[[ModItemInventoryItemCompositeDef _556_HP DisplayName]] "5.56 mm Hollow Point"),
	'DisplayNamePlural', T(851863869106, --[[ModItemInventoryItemCompositeDef _556_HP DisplayNamePlural]] "5.56 mm Hollow Point"),
	'colorStyle', "AmmoHPColor",
	'Description', T(480380205605, --[[ModItemInventoryItemCompositeDef _556_HP Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(124123620804, --[[ModItemInventoryItemCompositeDef _556_HP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No armor penetration\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>"),
	'MaxStacks', 500,
	'Caliber', "556",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
		PlaceObj('CaliberModification', {
			mod_add = -4,
			target_prop = "PenetrationClass",
		}),
	},
	'AppliedEffects', {
		"Bleeding",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_556_Match",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/556_nato_bullets_match.png",
	'DisplayName', T(698167806306, --[[ModItemInventoryItemCompositeDef _556_Match DisplayName]] "5.56 mm Match"),
	'DisplayNamePlural', T(111898963431, --[[ModItemInventoryItemCompositeDef _556_Match DisplayNamePlural]] "5.56 mm Match"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(812408999625, --[[ModItemInventoryItemCompositeDef _556_Match Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(925629938932, --[[ModItemInventoryItemCompositeDef _556_Match AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming"),
	'MaxStacks', 500,
	'Caliber', "556",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "AimAccuracy",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_556_Tracer",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/556_nato_bullets_tracer.png",
	'DisplayName', T(553775715287, --[[ModItemInventoryItemCompositeDef _556_Tracer DisplayName]] "5.56 mm Tracer"),
	'DisplayNamePlural', T(399661349753, --[[ModItemInventoryItemCompositeDef _556_Tracer DisplayNamePlural]] "5.56 mm Tracer"),
	'colorStyle', "AmmoTracerColor",
	'Description', T(199125015116, --[[ModItemInventoryItemCompositeDef _556_Tracer Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(731237568096, --[[ModItemInventoryItemCompositeDef _556_Tracer AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Hit enemies are <color EmStyle>Exposed</color> and lose the benefits of Cover"),
	'MaxStacks', 500,
	'Caliber', "556",
	'Modifications', {},
	'AppliedEffects', {
		"Exposed",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762NATO_AP",
	'object_class', "Ammo",
	'ScrapParts', 10,
	'Icon', "UI/Icons/Items/762_nato_bullets_armor_piercing.png",
	'DisplayName', T(290590514551, --[[ModItemInventoryItemCompositeDef _762NATO_AP DisplayName]] "7.62 mm NATO Armor Piercing"),
	'DisplayNamePlural', T(862337628607, --[[ModItemInventoryItemCompositeDef _762NATO_AP DisplayNamePlural]] "7.62 mm NATO Armor Piercing"),
	'colorStyle', "AmmoAPColor",
	'Description', T(951278049573, --[[ModItemInventoryItemCompositeDef _762NATO_AP Description]] "7.62 NATO ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(451891915125, --[[ModItemInventoryItemCompositeDef _762NATO_AP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Improved armor penetration"),
	'MaxStacks', 500,
	'Caliber', "762NATO",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "PenetrationClass",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762NATO_Basic",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/762_nato_basic.png",
	'DisplayName', T(595292057547, --[[ModItemInventoryItemCompositeDef _762NATO_Basic DisplayName]] "7.62 mm NATO Standard"),
	'DisplayNamePlural', T(262109690815, --[[ModItemInventoryItemCompositeDef _762NATO_Basic DisplayNamePlural]] "7.62 mm NATO Standard"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(151560406169, --[[ModItemInventoryItemCompositeDef _762NATO_Basic Description]] "7.62 NATO ammo for Assault Rifles, SMGs, and Machine Guns."),
	'MaxStacks', 500,
	'Caliber', "762NATO",
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762NATO_HP",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/762_nato_bullets_hollow_point.png",
	'DisplayName', T(265454549104, --[[ModItemInventoryItemCompositeDef _762NATO_HP DisplayName]] "7.62 mm NATO Hollow Point"),
	'DisplayNamePlural', T(772926698509, --[[ModItemInventoryItemCompositeDef _762NATO_HP DisplayNamePlural]] "7.62 mm NATO Hollow Point"),
	'colorStyle', "AmmoHPColor",
	'Description', T(699943246197, --[[ModItemInventoryItemCompositeDef _762NATO_HP Description]] "7.62 NATO ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(292088089137, --[[ModItemInventoryItemCompositeDef _762NATO_HP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No armor penetration\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>"),
	'MaxStacks', 500,
	'Caliber', "762NATO",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
		PlaceObj('CaliberModification', {
			mod_add = -4,
			target_prop = "PenetrationClass",
		}),
	},
	'AppliedEffects', {
		"Bleeding",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762NATO_Match",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/762_nato_bullets_match.png",
	'DisplayName', T(816377501981, --[[ModItemInventoryItemCompositeDef _762NATO_Match DisplayName]] "7.62 mm NATO Match"),
	'DisplayNamePlural', T(451955264155, --[[ModItemInventoryItemCompositeDef _762NATO_Match DisplayNamePlural]] "7.62 mm NATO Match"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(653265028863, --[[ModItemInventoryItemCompositeDef _762NATO_Match Description]] "7.62 NATO ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(105444974504, --[[ModItemInventoryItemCompositeDef _762NATO_Match AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming"),
	'MaxStacks', 500,
	'Caliber', "762NATO",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "AimAccuracy",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762NATO_Tracer",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/762_nato_bullets_tracer.png",
	'DisplayName', T(609896162589, --[[ModItemInventoryItemCompositeDef _762NATO_Tracer DisplayName]] "7.62 mm NATO Tracer"),
	'DisplayNamePlural', T(396485123376, --[[ModItemInventoryItemCompositeDef _762NATO_Tracer DisplayNamePlural]] "7.62 mm NATO Tracer"),
	'colorStyle', "AmmoTracerColor",
	'Description', T(544145114885, --[[ModItemInventoryItemCompositeDef _762NATO_Tracer Description]] "7.62 NATO ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(525715465109, --[[ModItemInventoryItemCompositeDef _762NATO_Tracer AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Hit enemies are <color EmStyle>Exposed</color> and lose the benefits of Cover"),
	'MaxStacks', 500,
	'Caliber', "762NATO",
	'Modifications', {},
	'AppliedEffects', {
		"Exposed",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762WP_AP",
	'object_class', "Ammo",
	'ScrapParts', 10,
	'Icon', "UI/Icons/Items/762_wp_bullets_armor_piercing.png",
	'DisplayName', T(575741321769, --[[ModItemInventoryItemCompositeDef _762WP_AP DisplayName]] "7.62 mm WP Armor Piercing"),
	'DisplayNamePlural', T(509526496588, --[[ModItemInventoryItemCompositeDef _762WP_AP DisplayNamePlural]] "7.62 mm WP Armor Piercing"),
	'colorStyle', "AmmoAPColor",
	'Description', T(306830054524, --[[ModItemInventoryItemCompositeDef _762WP_AP Description]] "7.62 Warsaw Pact ammo for Assault Rifles, SMGs, Machine Guns, and Snipers."),
	'AdditionalHint', T(188869339445, --[[ModItemInventoryItemCompositeDef _762WP_AP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Improved armor penetration"),
	'MaxStacks', 500,
	'Caliber', "762WP",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "PenetrationClass",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762WP_Basic",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/762_wp_bullets_basic.png",
	'DisplayName', T(290857637720, --[[ModItemInventoryItemCompositeDef _762WP_Basic DisplayName]] "7.62 mm WP Standard"),
	'DisplayNamePlural', T(725329731391, --[[ModItemInventoryItemCompositeDef _762WP_Basic DisplayNamePlural]] "7.62 mm WP Standard"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(839689203683, --[[ModItemInventoryItemCompositeDef _762WP_Basic Description]] "7.62 Warsaw Pact ammo for Assault Rifles, SMGs, Machine Guns, and Snipers."),
	'MaxStacks', 500,
	'Caliber', "762WP",
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762WP_HP",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/762_wp_bullets_hollow_point.png",
	'DisplayName', T(797678435066, --[[ModItemInventoryItemCompositeDef _762WP_HP DisplayName]] "7.62 mm WP Hollow Point"),
	'DisplayNamePlural', T(130173456141, --[[ModItemInventoryItemCompositeDef _762WP_HP DisplayNamePlural]] "7.62 mm WP Hollow Point"),
	'colorStyle', "AmmoHPColor",
	'Description', T(648063237806, --[[ModItemInventoryItemCompositeDef _762WP_HP Description]] "7.62 Warsaw Pact ammo for Assault Rifles, SMGs, Machine Guns, and Snipers."),
	'AdditionalHint', T(183704896156, --[[ModItemInventoryItemCompositeDef _762WP_HP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No armor penetration\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>"),
	'MaxStacks', 500,
	'Caliber', "762WP",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
		PlaceObj('CaliberModification', {
			mod_add = -4,
			target_prop = "PenetrationClass",
		}),
	},
	'AppliedEffects', {
		"Bleeding",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762WP_Match",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/762_wp_bullets_match.png",
	'DisplayName', T(366194229820, --[[ModItemInventoryItemCompositeDef _762WP_Match DisplayName]] "7.62 mm WP Match"),
	'DisplayNamePlural', T(241028501277, --[[ModItemInventoryItemCompositeDef _762WP_Match DisplayNamePlural]] "7.62 mm WP Match"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(144203148415, --[[ModItemInventoryItemCompositeDef _762WP_Match Description]] "7.62 Warsaw Pact ammo for Assault Rifles, SMGs, Machine Guns, and Snipers."),
	'AdditionalHint', T(873037222597, --[[ModItemInventoryItemCompositeDef _762WP_Match AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming"),
	'MaxStacks', 500,
	'Caliber', "762WP",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "AimAccuracy",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_762WP_Tracer",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/762_wp_bullets_tracer.png",
	'DisplayName', T(782482272628, --[[ModItemInventoryItemCompositeDef _762WP_Tracer DisplayName]] "7.62 mm WP Tracer"),
	'DisplayNamePlural', T(746573934898, --[[ModItemInventoryItemCompositeDef _762WP_Tracer DisplayNamePlural]] "7.62 mm WP Tracer"),
	'colorStyle', "AmmoTracerColor",
	'Description', T(160049026784, --[[ModItemInventoryItemCompositeDef _762WP_Tracer Description]] "7.62 Warsaw Pact ammo for Assault Rifles, SMGs, Machine Guns, and Snipers."),
	'AdditionalHint', T(737383126496, --[[ModItemInventoryItemCompositeDef _762WP_Tracer AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Hit enemies are <color EmStyle>Exposed</color> and lose the benefits of Cover"),
	'MaxStacks', 500,
	'Caliber', "762WP",
	'Modifications', {},
	'AppliedEffects', {
		"Exposed",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_9mm_AP",
	'object_class', "Ammo",
	'ScrapParts', 10,
	'Icon', "UI/Icons/Items/9mm_bullets_armor_piercing.png",
	'DisplayName', T(859387820909, --[[ModItemInventoryItemCompositeDef _9mm_AP DisplayName]] "9 mm Armor Piercing"),
	'DisplayNamePlural', T(323309130537, --[[ModItemInventoryItemCompositeDef _9mm_AP DisplayNamePlural]] "9 mm Armor Piercing"),
	'colorStyle', "AmmoAPColor",
	'Description', T(199950930386, --[[ModItemInventoryItemCompositeDef _9mm_AP Description]] "9 mm ammo for Handguns and SMGs."),
	'AdditionalHint', T(418764036018, --[[ModItemInventoryItemCompositeDef _9mm_AP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Improved armor penetration"),
	'MaxStacks', 500,
	'Caliber', "9mm",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "PenetrationClass",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_9mm_Basic",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/9mm_bullets_basic.png",
	'DisplayName', T(279696664684, --[[ModItemInventoryItemCompositeDef _9mm_Basic DisplayName]] "9 mm Standard"),
	'DisplayNamePlural', T(949789432253, --[[ModItemInventoryItemCompositeDef _9mm_Basic DisplayNamePlural]] "9 mm Standard"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(863576905264, --[[ModItemInventoryItemCompositeDef _9mm_Basic Description]] "9 mm ammo for Handguns and SMGs."),
	'MaxStacks', 500,
	'Caliber', "9mm",
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_9mm_HP",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/9mm_bullets_hollow_point.png",
	'DisplayName', T(186903402109, --[[ModItemInventoryItemCompositeDef _9mm_HP DisplayName]] "9 mm Hollow Point"),
	'DisplayNamePlural', T(201056654024, --[[ModItemInventoryItemCompositeDef _9mm_HP DisplayNamePlural]] "9 mm Hollow Point"),
	'colorStyle', "AmmoHPColor",
	'Description', T(143348710800, --[[ModItemInventoryItemCompositeDef _9mm_HP Description]] "9 mm ammo for Handguns and SMGs."),
	'AdditionalHint', T(327585201436, --[[ModItemInventoryItemCompositeDef _9mm_HP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No armor penetration\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>"),
	'MaxStacks', 500,
	'Caliber', "9mm",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
		PlaceObj('CaliberModification', {
			mod_add = -4,
			target_prop = "PenetrationClass",
		}),
	},
	'AppliedEffects', {
		"Bleeding",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_9mm_Match",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/9mm_bullets_match.png",
	'DisplayName', T(179951290481, --[[ModItemInventoryItemCompositeDef _9mm_Match DisplayName]] "9 mm Match"),
	'DisplayNamePlural', T(744008286315, --[[ModItemInventoryItemCompositeDef _9mm_Match DisplayNamePlural]] "9 mm Match"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(866336693485, --[[ModItemInventoryItemCompositeDef _9mm_Match Description]] "9 mm ammo for Handguns and SMGs."),
	'AdditionalHint', T(961594620499, --[[ModItemInventoryItemCompositeDef _9mm_Match AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Increased bonus from Aiming"),
	'MaxStacks', 500,
	'Caliber', "9mm",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "AimAccuracy",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_9mm_Shock",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/9mm_bullets_shock.png",
	'DisplayName', T(738167635201, --[[ModItemInventoryItemCompositeDef _9mm_Shock DisplayName]] "9 mm Shock"),
	'DisplayNamePlural', T(436165943960, --[[ModItemInventoryItemCompositeDef _9mm_Shock DisplayNamePlural]] "9 mm Shock"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(203130139171, --[[ModItemInventoryItemCompositeDef _9mm_Shock Description]] "9 mm ammo for Handguns and SMGs."),
	'AdditionalHint', T(472504585535, --[[ModItemInventoryItemCompositeDef _9mm_Shock AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Reduced range\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No armor penetration\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Hit enemies are <color EmStyle>Exposed</color> and lose the benefits of Cover\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Inflicts <color EmStyle>Bleeding</color>"),
	'MaxStacks', 500,
	'Caliber', "9mm",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
		PlaceObj('CaliberModification', {
			mod_add = -4,
			target_prop = "PenetrationClass",
		}),
		PlaceObj('CaliberModification', {
			mod_add = -4,
			target_prop = "WeaponRange",
		}),
	},
	'AppliedEffects', {
		"Exposed",
		"Bleeding",
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_9mm_Subsonic",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/9mm_bullets_subsonic.png",
	'DisplayName', T(195640092295, --[[ModItemInventoryItemCompositeDef _9mm_Subsonic DisplayName]] "9 mm Subsonic"),
	'DisplayNamePlural', T(637301715850, --[[ModItemInventoryItemCompositeDef _9mm_Subsonic DisplayNamePlural]] "9 mm Subsonic"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(848025590882, --[[ModItemInventoryItemCompositeDef _9mm_Subsonic Description]] "9 mm ammo for Handguns and SMGs."),
	'AdditionalHint', T(868544024316, --[[ModItemInventoryItemCompositeDef _9mm_Subsonic AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Less noisy"),
	'MaxStacks', 500,
	'Caliber', "9mm",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_mul = 500,
			target_prop = "Noise",
		}),
	},
	'GunPowder', 1,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_9mm_Tracer",
	'object_class', "Ammo",
	'ScrapParts', 5,
	'Icon', "UI/Icons/Items/9mm_bullets_tracer.png",
	'DisplayName', T(803745141125, --[[ModItemInventoryItemCompositeDef _9mm_Tracer DisplayName]] "9 mm Tracer"),
	'DisplayNamePlural', T(693836143344, --[[ModItemInventoryItemCompositeDef _9mm_Tracer DisplayNamePlural]] "9 mm Tracer"),
	'colorStyle', "AmmoTracerColor",
	'Description', T(684499498676, --[[ModItemInventoryItemCompositeDef _9mm_Tracer Description]] "9 mm ammo for Handguns and SMGs."),
	'AdditionalHint', T(109038412193, --[[ModItemInventoryItemCompositeDef _9mm_Tracer AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Hit enemies are <color EmStyle>Exposed</color> and lose the benefits of Cover"),
	'MaxStacks', 500,
	'Caliber', "9mm",
	'AppliedEffects', {
		"Exposed",
	},
	'GunPowder', 1,
}),
}
