return PlaceObj('ModDef', {
	'title', "JA3ScrapAmmoMod",
	'description', "This mod enables players to break down their ammo for scrap and gunpowder\n\nDefault: \nNormal bullets:2 scrap and 1 gunpowder per 30x bullets\nAP bullets: 4 scrap and 1 gunpowder per 30x bullets",
	'image', "Mod/JA3ScrapAmmoMod/images/Preview.png",
	'last_changes', "Initial Upload",
	'id', "JA3ScrapAmmoMod",
	'content_path', "Mod/JA3ScrapAmmoMod/",
	'author', "thej33per",
	'version_major', 1,
	'version_minor', 1,
	'version', 17,
	'lua_revision', 233360,
	'saved_with_revision', 339125,
	'code', {
		"Code/AmmoProperties.lua",
		"Code/AmountGunPowderFromAmmo.lua",
		"Code/AmountScrapPartsFromAmmo.lua",
		"Code/GetInventoryObject.lua",
		"Code/GetScrapParts.lua",
		"Code/InventoryStackAddAndStackGunpowder.lua",
		"Code/ScrapItem.lua",
		"Code/AmmoObjects.lua",
	},
	'saved', 1691102195,
	'code_hash', -5694483596211022361,
	'screenshot1', "Mod/JA3ScrapAmmoMod/images/Screenshot_1.png",
	'screenshot2', "Mod/JA3ScrapAmmoMod/images/Screenshot_2.png",
	'steam_id', "3011823537",
})