return PlaceObj('ModDef', {
	'title', "JA3ScrapAmmoMod",
	'description', "This mod enables players to break down their ammo for scrap and gunpowder\n\nDefault: \nNormal bullets:2 scrap and 1 gunpowder per 30x bullets\nAP bullets: 4 scrap and 1 gunpowder per 30x bullets\n\nCompatible with: Descriptive Ammo Icons\nNot Compatible with: ScrapMore!, Parts From Salvage x3",
	'image', "Mod/JA3ScrapAmmoMod/images/Preview.png",
	'last_changes', "Setting ScrapParts and GunPowder in Ammo-Objects via Script\nRemoving Inventory Items for Ammo\n(thx to Audaki_ra)",
	'id', "JA3ScrapAmmoMod",
	'author', "thej33per",
	'version_major', 1,
	'version_minor', 20,
	'version', 23,
	'lua_revision', 233360,
	'saved_with_revision', 346319,
	'code', {
		"Code/AmmoProperties.lua",
		"Code/AmountGunPowderFromAmmo.lua",
		"Code/AmountScrapPartsFromAmmo.lua",
		"Code/GetInventoryObject.lua",
		"Code/GetScrapParts.lua",
		"Code/InitMod.lua",
		"Code/InventoryAddAndStack.lua",
		"Code/ScrapItem.lua",
	},
	'has_options', true,
	'saved', 1701606298,
	'code_hash', -4528378392620926450,
	'screenshot1', "Mod/JA3ScrapAmmoMod/images/Screenshot_1.png",
	'screenshot2', "Mod/JA3ScrapAmmoMod/images/Screenshot_2.png",
	'steam_id', "3011823537",
})