return PlaceObj('ModDef', {
	'title', "JA3ScrapAmmoMod",
	'description', "This mod enables players to break down their ammo for scrap and gunpowder",
	'id', "JA3ScrapAmmoMod",
	'content_path', "Mod/JA3ScrapAmmoMod/",
	'author', "thej33per",
	'version_minor', 1,
	'version', 50,
	'lua_revision', 233360,
	'saved_with_revision', 338408,
	'code', {
		"Code/AmmoProperties.lua",
		"Code/AmountGunPowderFromAmmo.lua",
		"Code/AmountScrapPartsFromAmmo.lua",
		"Code/GetScrapParts.lua",
		"Code/ScrapItem.lua",
		"Code/GetInventoryObject.lua",
		"InventoryItem/_12gauge_Breacher.lua",
		"InventoryItem/_12gauge_Buckshot.lua",
		"InventoryItem/_12gauge_Flechette.lua",
		"InventoryItem/_12gauge_Saltshot.lua",
		"InventoryItem/_44CAL_AP.lua",
		"InventoryItem/_44CAL_Basic.lua",
		"InventoryItem/_44CAL_HP.lua",
		"InventoryItem/_44CAL_Match.lua",
		"InventoryItem/_44CAL_Shock.lua",
		"InventoryItem/_50BMG_Basic.lua",
		"InventoryItem/_50BMG_HE.lua",
		"InventoryItem/_50BMG_Incendiary.lua",
		"InventoryItem/_50BMG_SLAP.lua",
		"InventoryItem/_556_AP.lua",
		"InventoryItem/_556_Basic.lua",
		"InventoryItem/_556_HP.lua",
		"InventoryItem/_556_Match.lua",
		"InventoryItem/_556_Tracer.lua",
		"InventoryItem/_762NATO_AP.lua",
		"InventoryItem/_762NATO_Basic.lua",
		"InventoryItem/_762NATO_HP.lua",
		"InventoryItem/_762NATO_Match.lua",
		"InventoryItem/_762NATO_Tracer.lua",
		"InventoryItem/_762WP_AP.lua",
		"InventoryItem/_762WP_Basic.lua",
		"InventoryItem/_762WP_HP.lua",
		"InventoryItem/_762WP_Match.lua",
		"InventoryItem/_762WP_Tracer.lua",
		"InventoryItem/_9mm_AP.lua",
		"InventoryItem/_9mm_Basic.lua",
		"InventoryItem/_9mm_HP.lua",
		"InventoryItem/_9mm_Match.lua",
		"InventoryItem/_9mm_Shock.lua",
		"InventoryItem/_9mm_Subsonic.lua",
		"InventoryItem/_9mm_Tracer.lua",
	},
	'saved', 1690495653,
	'code_hash', -3128983038789159495,
})